export interface Relationship {
  from: string
  to: string
  type: "1:1" | "1:N" | "N:M" | "N:1"
  via?: string
  foreignKey: string
  references: string
  onDelete: "CASCADE" | "SET NULL" | "RESTRICT" | "NO ACTION"
  description: string
}

export const ENTITY_RELATIONSHIPS: Relationship[] = [
  {
    from: "users",
    to: "profiles",
    type: "1:1",
    foreignKey: "user_id",
    references: "users(id)",
    onDelete: "CASCADE",
    description: "Every user has exactly one profile",
  },
  {
    from: "users",
    to: "workspaces",
    type: "1:N",
    foreignKey: "created_by",
    references: "users(id)",
    onDelete: "SET NULL",
    description: "A user can create multiple workspaces",
  },
  {
    from: "users",
    to: "workspace_members",
    type: "1:N",
    foreignKey: "user_id",
    references: "users(id)",
    onDelete: "CASCADE",
    description: "A user can be a member of multiple workspaces",
  },
  {
    from: "users",
    to: "transactions",
    type: "1:N",
    foreignKey: "created_by",
    references: "users(id)",
    onDelete: "SET NULL",
    description: "A user can create many transactions",
  },
  {
    from: "users",
    to: "recurring_transactions",
    type: "1:N",
    foreignKey: "created_by",
    references: "users(id)",
    onDelete: "CASCADE",
    description: "A user can create many recurring transactions",
  },
  {
    from: "users",
    to: "budgets",
    type: "1:N",
    foreignKey: "user_id",
    references: "users(id)",
    onDelete: "CASCADE",
    description: "A user can have multiple budgets",
  },
  {
    from: "users",
    to: "notifications",
    type: "1:N",
    foreignKey: "user_id",
    references: "users(id)",
    onDelete: "CASCADE",
    description: "A user can receive many notifications",
  },
  {
    from: "users",
    to: "activity_logs",
    type: "1:N",
    foreignKey: "user_id",
    references: "users(id)",
    onDelete: "SET NULL",
    description: "A user can generate many activity log entries",
  },
  {
    from: "users",
    to: "workspace_invitations",
    type: "1:N",
    foreignKey: "invited_by",
    references: "users(id)",
    onDelete: "CASCADE",
    description: "A user can send many invitations",
  },
  {
    from: "workspaces",
    to: "workspace_members",
    type: "1:N",
    foreignKey: "workspace_id",
    references: "workspaces(id)",
    onDelete: "CASCADE",
    description: "A workspace has many members",
  },
  {
    from: "workspaces",
    to: "transactions",
    type: "1:N",
    foreignKey: "workspace_id",
    references: "workspaces(id)",
    onDelete: "SET NULL",
    description: "A workspace has many transactions",
  },
  {
    from: "workspaces",
    to: "recurring_transactions",
    type: "1:N",
    foreignKey: "workspace_id",
    references: "workspaces(id)",
    onDelete: "CASCADE",
    description: "A workspace can have many recurring transactions",
  },
  {
    from: "workspaces",
    to: "budgets",
    type: "1:N",
    foreignKey: "workspace_id",
    references: "workspaces(id)",
    onDelete: "CASCADE",
    description: "A workspace can have many budgets",
  },
  {
    from: "workspaces",
    to: "categories",
    type: "1:N",
    foreignKey: "workspace_id",
    references: "workspaces(id)",
    onDelete: "CASCADE",
    description: "A workspace can have custom categories",
  },
  {
    from: "workspaces",
    to: "activity_logs",
    type: "1:N",
    foreignKey: "workspace_id",
    references: "workspaces(id)",
    onDelete: "CASCADE",
    description: "A workspace generates activity logs",
  },
  {
    from: "workspaces",
    to: "workspace_invitations",
    type: "1:N",
    foreignKey: "workspace_id",
    references: "workspaces(id)",
    onDelete: "CASCADE",
    description: "A workspace can have many invitations",
  },
  {
    from: "categories",
    to: "transactions",
    type: "1:N",
    foreignKey: "category_id",
    references: "categories(id)",
    onDelete: "RESTRICT",
    description: "A category can be used by many transactions",
  },
  {
    from: "categories",
    to: "recurring_transactions",
    type: "1:N",
    foreignKey: "category_id",
    references: "categories(id)",
    onDelete: "RESTRICT",
    description: "A category can be used by many recurring transactions",
  },
  {
    from: "categories",
    to: "budgets",
    type: "1:N",
    foreignKey: "category_id",
    references: "categories(id)",
    onDelete: "CASCADE",
    description: "A category can have a budget assigned",
  },
  {
    from: "transactions",
    to: "recurring_transactions",
    type: "1:1",
    foreignKey: "last_transaction_id",
    references: "transactions(id)",
    onDelete: "SET NULL",
    description: "A recurring transaction can reference the last generated transaction",
  },
  {
    from: "workspace_members",
    to: "users",
    type: "N:1",
    foreignKey: "user_id",
    references: "users(id)",
    onDelete: "CASCADE",
    description: "Many members reference one user",
  },
  {
    from: "workspace_members",
    to: "workspaces",
    type: "N:1",
    foreignKey: "workspace_id",
    references: "workspaces(id)",
    onDelete: "CASCADE",
    description: "Many members reference one workspace",
  },
]

export const ENTITY_CARDINALITY: Record<string, { min: number; max: number | "N" }> = {
  users: { min: 0, max: "N" },
  profiles: { min: 0, max: 1 },
  workspaces: { min: 0, max: 10 },
  workspace_members: { min: 0, max: 50 },
  workspace_invitations: { min: 0, max: 50 },
  categories: { min: 0, max: 100 },
  transactions: { min: 0, max: "N" },
  recurring_transactions: { min: 0, max: 50 },
  budgets: { min: 0, max: 50 },
  notifications: { min: 0, max: "N" },
  activity_logs: { min: 0, max: "N" },
}
